name: Docker Image mosquitto

on:
  push:
    branches:
      - master

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: "bboykin87/mosquitto"
          TAG_NAME: "v0.1"
          LATEST: "true"

     
    #- uses: actions/checkout@v2
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag bboykin87/mosquitto:$(date +%s)
